# Streamlit Cloud Secrets - Tam Format

# Google Sheets configuration (En üstte olmalı)
GOOGLE_SHEET_ID = "1XzHbtgOl6AOE-lg7y-E3z_G6dZ2gcvxb004Coxa6g8A"

# Google Cloud Service Account credentials
[gcp_service_account]
type = "service_account"
project_id = "your-actual-project-id"
private_key_id = "your-actual-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_ACTUAL_PRIVATE_KEY\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-actual-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/oauth2/v3/certs/your-service-account%40your-project.iam.gserviceaccount.com"
